image: "python:3.8"

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
#services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest

#variables:
#  POSTGRES_DB: database_name
# Cache packages in between builds

cache:
  paths:
    - vendor/python

# This is a basic example for a packages or script which doesn't use
# services such as redis or postgres
before_script:
  # Setup git
  - apt-get update
  - apt-get install -y git
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - pip install -r requirements.txt


test:
  script:
  - pytest --mypy --cov {{ cookiecutter.project_name }} --cov-report xml:cov.xml --cov-report term-missing --verbose

# artifactory:
#   script:
#     - pip install twine
#     - python setup.py sdist
#     - python setup.py bdist_wheel
#     - twine upload --config-file .pypirc -r local dist/*
