exclude: '^docs/conf.py'

repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=no']

- repo: http://github.com/timothycrosley/isort
  rev: 5.6.4
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/asottile/blacken-docs
  rev: v1.8.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black]

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear]

- repo: https://github.com/asottile/pyupgrade # A tool to automatically upgrade syntax for newer versions of the language.

  rev: v2.10.0
  hooks:
    -   id: pyupgrade

- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.5.7
  hooks:
  - id: nbqa-black
    additional_dependencies: [ black==20.8b1 ]
    args: [--nbqa-mutate ]
  - id: nbqa-isort
    additional_dependencies: [ isort==5.6.4 ]
    args: [ --nbqa-mutate, --profile=black, --project=pandas_profiling ]
  - id: nbqa-pyupgrade
    additional_dependencies: [ pyupgrade==2.7.3 ]
    args: [ --nbqa-mutate, --py36-plus ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]